Add the TIC book‘s weaponry.xml  zh_CN version
GTNewHorizons/TinkersConstruct pull request #111
Opened 2024-02-09 18:30 UTC by NealDeal34

2024-02-17 13:33 UTC, Nxer requested changes
机翻严重，再人工翻阅润色一下吧。

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> + <text>发射物</text>
弹射物 或 弹药 会不会更让人耳熟能详一点

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +这些远程武器没有耐久值，但每次投掷/射击都会消耗弹药。</text>
`这些远程武器没有耐久值` → `这些“弹药”没有耐久值`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +投枪：
`投枪` → `标枪`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +投掷会有一个小的目标点。由于它们的尺寸，你只能携带几支，但它们效果显著。</text>
`但它们效果显著` → `但它们伤害显著`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +这把武器由两个弓臂和一根弓弦组合而成，是一把快速方便的弓。请记住，用像石头这样的不灵活材料制作弓弩将很难收回，也不能很好地加速弹丸。有机材料是短弓的首选材料，而金属需要很大的力量来收回，但也大幅提高了杀伤力。
- `是一把快速方便的弓` → `是一把轻便快捷的弓`
 - `用像石头这样的不灵活材料制作弓弩将很难收回` → `用像石头这样质地生硬的材料制作弓弩将很难拉开弓`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +弓上的攻击性附魔不会作用于箭矢。影响其远程性能的唯一改良剂是红石和青金石。</text>
`影响其远程性能的唯一改良剂是红石和青金石` → `只有红石和青金石强化可以增强其远程攻击效果`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +那些讨厌的金属材料弓弩很难收回。幸运的是，良匠知道如何自救！弩可以让你用弓闩预先装填，并随时准备开火。由于这允许更大的威力，它可以发射更重的炮弹，从而造成更多的伤害和装甲穿透。
- `那些讨厌的金属材料弓弩很难收回` → `那些讨厌的金属材料弓弩很难拉动`
 - `弩可以让你用弓闩预先装填` → `弩可以预装填弹药`
 - `由于这允许更大的威力` → `因此弩可以更具威力`
 - `更重的炮弹` → `更重的弩箭`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +要装载十字弩，只需单击右键并等待动画完成。在潜行时按右键可停止加载过程。它可以用同样的方法卸载。</text>
`在潜行时按右键可停止加载过程。它可以用同样的方法卸载。` → `在潜行时按右键可以停止装载弹药或卸载已装载的弹药。`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +制作弩箭是一个微妙的过程。首先，你需要一个手柄形式的芯。
- `微妙` → `细致`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +将这根手柄到冶炼厂，并将其放入浇筑台。将一些金属倒在上面，在尖端涂上更具破坏性的材料。
全句转换成 `把这根手柄放到冶炼厂的浇筑台上，用高伤害材料浇筑其一头。`

2024-02-17 13:33 UTC, Nxer commented on src/main/resources/assets/tinker/manuals/zh_CN/weaponry.xml
> +完成此过程后，添加一个箭羽，即可使用弩箭。
`完成此过程后，和箭羽一起组织成弩箭就好了。`

2024-02-17 14:44 UTC, Kiwi233 requested changes
感谢你的提醒，匠魂手册我们还未进行很好的翻译。
不过你提交的汉化里存在不少机翻，需要进行修改才能接受，如果愿意进一步联系，请加入汉化组QQ群：264817549

2024-02-18 15:44 UTC, Nxer approved these changes

2024-03-03 16:06 UTC, chochem commented
All translations are now handled in a new coordinated effort at at https://discord.com/channels/181078474394566657/1211323236260778124
please come by there :)

2024-03-03 16:06 UTC, closed without merging