Mod Friendly Piercing (Rapier, Arrow & Bolts)
GTNewHorizons/TinkersConstruct pull request #60
Opened 2022-12-25 14:15 UTC by DrParadox7

Piercing damage will now only pierce through armor values.
It will no longer go through invincibility, blocking or even armors with higher armor value than diamond.

Piercing damage converted to bonus damage equivalent to victim's armor protection (capped at diamond armor).
`So if player has 25 armor (diamond set is 20), the rapier damage will only be reduced by the 5 armor.`

This prevents rapiers from bypassing immunities.

2022-12-26 17:40 UTC, OneEyeMaker requested changes

2022-12-26 17:40 UTC, OneEyeMaker commented on src/main/java/tconstruct/library/tools/AbilityHelper.java
> +                        damage = (int) (damage / (1 - (0.04 * armorValue)));
Am I understanding correctly that rapier wiil do 5 times more damage against diamond+ armor?

2022-12-26 17:40 UTC, OneEyeMaker commented on src/main/java/tconstruct/library/util/PiercingArrowDamage.java
> +        // this.setDamageBypassesArmor();
Do not comment code that becomes needless. Just delete it (to prevent confusion about its necessity). *If* this code will be needed later, one can be found easily using Git.

2022-12-26 17:40 UTC, OneEyeMaker commented on src/main/java/tconstruct/library/util/PiercingEntityDamage.java
> +        //       this.setDamageBypassesArmor();
Same as above.

2022-12-26 18:27 UTC, DrParadox7 commented on src/main/java/tconstruct/library/tools/AbilityHelper.java
> +                        damage = (int) (damage / (1 - (0.04 * armorValue)));
Correct.
This reverse engineers the armor calculation from Minecraft:

A full set of diamond armor protects 80% so multiplying the damage by 5 will counteract that.
Better than just setting the damage to unblockable

2022-12-27 05:52 UTC, OneEyeMaker approved these changes

2022-12-27 08:11 UTC, merged

2023-11-16 19:12 UTC, brandyyn commented
can this be a config option?

2023-11-16 19:19 UTC, bombcar commented
> can this be a config option?

It wouldn't be impossible, but if the goal is to just bypass content, there's other ways to do that already

2023-11-16 19:21 UTC, brandyyn commented
> > can this be a config option?
> 
> It wouldn't be impossible, but if the goal is to just bypass content, there's other ways to do that already

I'd like to be able to have full piercing in my modpack

2023-11-16 20:59 UTC, vovaksenov commented
Since TiC is listed under "active" support, it might be reasonable to implement a config option if someone has the time.

2023-11-16 22:32 UTC, brandyyn commented
> Since TiC is listed under "active" support, it might be reasonable to implement a config option if someone has the time.

im no mod dev yet but shouldn't this just be as easy as an "if-else" statement for the new code versus the original code for the rapier..?

2023-11-16 23:22 UTC, vovaksenov commented
Sure, it really shouldnt be hard, you can do it yourself anytime 😇
On a more serious note, this issue is low priority, so the devs might take a while to get to this. It is not only about how difficult it is, but also whether anyone wants to do it at all when they could be doing much more interesting stuff..

2023-11-16 23:23 UTC, vovaksenov commented
Also, this is an old pr discussion, you should make an actual issue to move the discussion there.

2023-11-16 23:23 UTC, brandyyn commented
> Sure, it really shouldnt be hard, you can do it yourself anytime 😇 On a more serious note, this issue is low priority, so the devs might take a while to get to this. It is not only about how difficult it is, but also whether anyone wants to do it at all when they could be doing much more interesting stuff..

happy to do it when i know more about modding! i just started learning C++ as a part of my course.

2023-11-16 23:29 UTC, bombcar commented
https://github.com/GTNewHorizons/ThaumicTinkerer/pull/35/files is similar and 

And https://gtnh.miraheze.org/wiki/Development#Next_steps 

If you can’t do it yourself create a new issue and @ me maybe I’ll get to it maybe not

2023-11-16 23:33 UTC, Dream-Master commented
Everything can be a config option . If you like cheating play another pack.

2023-11-16 23:34 UTC, brandyyn commented
> Everything can be a config option . If you like cheating play another pack.

I literally said the option would be for my own pack

2023-11-16 23:35 UTC, Dream-Master commented
Then exclude this pr and build your own version.

2023-11-16 23:41 UTC, brandyyn commented
> Then exclude this pr and build your own version.



> > Sure, it really shouldnt be hard, you can do it yourself anytime 😇 On a more serious note, this issue is low priority, so the devs might take a while to get to this. It is not only about how difficult it is, but also whether anyone wants to do it at all when they could be doing much more interesting stuff..
> 
> happy to do it when i know more about modding! i just started learning C++ as a part of my course.