Misc Additions
GTNewHorizons/TinkersConstruct pull request #62
Opened 2022-12-25 15:57 UTC by DrParadox7

-Prevent Casting of Invalid Clay Casts.
-Prevent Clay Casts replacing Metal Casts from being used as the default cast in some addons.
-Added Nether Seared Channel.
-Added Blank Clay Cast as per request.

2022-12-27 09:36 UTC, minecraft7771 requested changes

2022-12-27 09:36 UTC, minecraft7771 commented on src/main/java/tconstruct/smeltery/TinkerSmeltery.java
> +                    if (iter < 14 || iter == 22 || iter == 25) {
Please refactor these into constant variables. It makes it hard to read.

2022-12-27 09:36 UTC, minecraft7771 commented on src/main/java/tconstruct/weaponry/TinkerWeaponry.java
> +                    if (i == 3) {
Here too.

2022-12-27 11:18 UTC, DrParadox7 commented on src/main/java/tconstruct/smeltery/TinkerSmeltery.java
> +                    if (iter < 14 || iter == 22 || iter == 25) {
I would prefer the clay cast  were kept mirroring the metal cast methods as well as being in the same location code wise

2022-12-27 11:49 UTC, minecraft7771 commented on src/main/java/tconstruct/smeltery/TinkerSmeltery.java
> +                    if (iter < 14 || iter == 22 || iter == 25) {
Sure but its hard to understand at first what 14, 22, 25 are so putting them into constant variables to give them a name would help.

2022-12-27 22:43 UTC, minecraft7771 requested changes

2022-12-27 22:43 UTC, minecraft7771 commented on src/main/java/tconstruct/weaponry/TinkerWeaponry.java
> +                    int castBowLimb = 3;
Since this is a constant it has no need to be here. Move it outside the method into the general scope of the class as `static final int CAST_BOW_LIMB = 3`

2022-12-29 18:43 UTC, minecraft7771 approved these changes

2022-12-29 18:50 UTC, merged