slimeBoots and slimeSling
GTNewHorizons/TinkersConstruct pull request #93
Opened 2023-09-03 13:07 UTC by Quetz4l

* changed items directories and some code
* slime sling now with durability to 100
* boots now reduce bounce instead of increasing it
* added vanilla recipes

2023-09-08 16:34 UTC, BlueWeabo reviewed
Thanks for the work! Just some minor things to address

2023-09-08 16:34 UTC, BlueWeabo commented on src/main/java/tconstruct/gadgets/TinkerGadgets.java
Are you sure removing this file won't cause any errors in full pack? Have you tested that no TC addon uses it?

2023-09-08 16:34 UTC, BlueWeabo commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        return String.format("%s:%s", "tinker", res);
any reason this is here? as it was from TinkerGadgets.java, which would make sense that it should either be left there or be put in TConstruct.java

2023-09-08 16:34 UTC, BlueWeabo commented on src/main/java/tconstruct/library/SlimeBounceHandler.java
> +                    // TConstruct.logger.info("Found boots in slot "+i);
any reason you need to leave the debug code in here?

2023-09-08 16:34 UTC, BlueWeabo commented on src/main/java/tconstruct/armor/TinkerArmor.java
As you have edited some of this file, could you also remove any wildcard imports there are here?

2023-09-08 16:34 UTC, BlueWeabo commented on src/main/java/tconstruct/TConstruct.java
Can you remove wildcard imports from the file if you can?

2023-09-08 16:54 UTC, Quetz4l commented on src/main/java/tconstruct/TConstruct.java
ok

2023-09-08 17:23 UTC, OneEyeMaker requested changes
I'm not completely happy with removal of Gadgets feature. Tinkers' Gadgets is special module for little useful things. And it should be there for such this like slime boots.
You also shouldn't mix removal/refactoring PRs with balancing ones: I think this PR should focus on balancing.

Also please recheck your math. With this PR slime sling becomes uncontrollable - in my play test it moves player about 50 blocks away after holding it little more than 1 second!

2023-09-08 17:23 UTC, OneEyeMaker commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeBoots.java
> +        this.setUnlocalizedName(getUnlocalizedName());
You should either use `setUnlocalizedName(...)` with exact name or override `getUnlocalizedName()` / `getUnlocalizedName(ItemStack stack)`.
Remove this line.

2023-09-08 17:23 UTC, OneEyeMaker commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeBoots.java
> +        return String.format("%s.%s", TConstruct.modID, "slime_boots".toLowerCase(Locale.US));
```suggestion
        return String.format("%s.%s", TConstruct.modID, "slime_boots");
```

2023-09-08 17:23 UTC, OneEyeMaker commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        this.setUnlocalizedName(getUnlocalizedName());
Same as above.

2023-09-08 17:23 UTC, OneEyeMaker commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        return 50000;
Why did you select this value?

2023-09-08 17:26 UTC, OneEyeMaker commented on src/main/java/tconstruct/gadgets/TinkerGadgets.java
Removal of this class already has side-effect: creative tab for slime boots has no icon.

2023-09-09 08:40 UTC, Quetz4l commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        return 50000;
To slightly speed up use and reduce the jump range, but yeah, it's still a long range

2023-09-09 10:40 UTC, Quetz4l commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        return 50000;
I wanted to speed up a bit and reduce the strength of the jumps, but now I see that it doesn't reduce the strength of the jumps.

2023-09-09 10:41 UTC, Quetz4l commented
what are the values for the jumps? Up and away?

2023-09-09 11:10 UTC, OneEyeMaker commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        return 50000;
This value represents maximum time (in game ticks) which item can be held (using right-click).
It should be equal 72000 ticks = 20 * 3600 seconds = 1 hour.

2023-09-09 11:15 UTC, OneEyeMaker commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        f = Math.min((f * f + f * 2.0F) * (4.0F / 3.0F), 6.0F);
I think these calculations cause 50+ blocks jumping. Increase divider of `f` from 5 to 20 (like in original code) or even more. Also you can play little bit with final multiplier of `f` (4).

2023-09-09 11:16 UTC, OneEyeMaker commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeBoots.java
> +            double velocity = gravity * time / 2;
I don't think that this value should be touched. Needs play-testing.

2023-09-09 11:18 UTC, Quetz4l commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeBoots.java
> +            double velocity = gravity * time / 2;
without it, the bounce increases every time and you go higher and higher.

2023-09-09 11:19 UTC, Quetz4l commented on src/main/java/tconstruct/armor/items/slime/ItemSlimeSling.java
> +        f = Math.min((f * f + f * 2.0F) * (4.0F / 3.0F), 6.0F);
I've rewired the formula, and I'm just wondering what length to put in

2023-09-09 17:35 UTC, OneEyeMaker approved these changes

2023-09-09 17:42 UTC, merged