feat: add ukrainian localization
GTNewHorizons/TinkersConstruct pull request #94
Opened 2023-09-06 14:31 UTC by Oleksey-Korolenko

2023-10-13 20:30 UTC, LewisSaber requested changes
Very very good translation

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +entity.TConstruct.KingSlime.name=Король слиз
what about "Король слизнів"?

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +achievement.tconstruct.proTinkerer.desc=Створіть свій перший 2 рівня інструмент
Створіть свій перший  інструмент 2 рівня

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +metalblock.tooltip=Подходит для основы маяка
Підходить для основи маяка, wrong language translation for above 2 lmao

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +smeltery.drain.tooltip1=Працює як вхідний і вихідний для
Працює як вхід і вихід для

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +gui.toolstation.pickaxe.desc=Кайло - це точний гірничий інструмент. Ефективна при роботі з каменем і рудами.\n\nНеобхідні частини:\n- Навершя кайла\n- Кріплення\n- стрижень
Ефективний, чоловічий рід

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +gui.toolstation.shortbow.desc=Короткий лук - це зброя для стрільби на великі відстані. Він швидко і точно випускає стріли у ворога.\n\nШвидкість стрільби: Швидка\n\nНеобхідні деталі:\n- тятива\n- пле
це зброя дальньої дії

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +material.netherrack=камінь Нижнього світу
Камінь з великої

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +tool.core.broken=Зламан
Зламано

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +armor.core.broken=Зламан
Зламано

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +armor.travelwings.ability=Функція: Высокий прыжок
Високий стрибок, again wrong language

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +modifier.toolstation.LeadBoots=Свинцові чоботи
Свинцеві чоботи

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +modifier.toolstation.Redstone=Redstone
Редстоун або Червоний камінь

2023-10-13 20:30 UTC, LewisSaber commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +modifier.tooltip.LeadBoots=Свинцові чоботи
Свинцеві чоботи

2023-10-14 03:06 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +crafters.Frypan=Сковорода
"Жаровня"

2023-10-14 03:17 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +infitool.fryingpan=Сковорода
"Жаровня"

2023-10-14 03:18 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +item.tconstruct.Pattern.frypan.name=Шаблон сковороди
"Шаблон жаровні"

2023-10-14 03:19 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +item.tconstruct.MetalPattern.frypan.name=Зліпок сковороди
"Зліпок жаровні"

2023-10-14 03:21 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +item.tconstruct.ClayPattern.frypan.name=Глиняний зліпок сковороди
"Глиняний зліпок жаровні"

2023-10-14 03:28 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +block.slime.tallgrass.name=Слизька трава
"Слизова" etc

2023-10-14 03:30 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +toolpart.FrypanHead=%%material сковорода
"жаровня"

2023-10-14 03:35 UTC, lordIcocain commented on src/main/resources/assets/tinker/lang/uk_UA.lang
> +modifier.tooltip.SlimySoles=Слизьові підошви
слизові

2023-10-28 14:05 UTC, merged